### ISSUE TITLE
NullPointerException while publish coverage report (v1.02)

### ISSUE THREAD

**Issue by pvvarfalameev** [jenkinsci/opencover-plugin#10]
![image](https://user-images.githubusercontent.com/83452741/126081618-d91c8c92-f14e-4690-adfe-2970775a4c40.png)
Get a null pointer exception during import opencover report, v.1.0.3
```node {
    stage('Preparation') {
        publishCoverage adapters: [opencoverAdapter(mergeToOneReport: true, path: 'coverage.xml')], sourceFileResolver: sourceFiles('NEVER_STORE')
    }
}

**Comment by jonesbusy** [comment]
Can you attach an opencover XML file that raise this NullPointer ?

**Comment by jonesbusy** [comment]
Plugin is deprecated and user must switch to the coverage plugin that now integrates the OpenCover format
