### ISSUE TITLE
Missing test report in BlueOcean's tests tab

### ISSUE THREAD

**Issue by thopiekar** [jenkinsci/opencover-plugin#12]
### Jenkins and plugins versions report

Jenkins: 2.346.2
OS: Linux - 5.10.0-15-amd64
---
Office-365-Connector:4.17.0
ace-editor:1.1
allure-jenkins-plugin:2.30.2
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
authorize-project:1.4.0
azure-ad:241.vb_e5cd7c35b_2e
azure-sdk:118.v43f74dd9ca_dc
blueocean:1.25.5
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.25.5
blueocean-commons:1.25.5
blueocean-config:1.25.5
blueocean-core-js:1.25.5
blueocean-dashboard:1.25.5
blueocean-display-url:2.4.1
blueocean-events:1.25.5
blueocean-git-pipeline:1.25.5
blueocean-github-pipeline:1.25.5
blueocean-i18n:1.25.5
blueocean-jwt:1.25.5
blueocean-personalization:1.25.5
blueocean-pipeline-api-impl:1.25.5
blueocean-pipeline-editor:1.25.5
blueocean-pipeline-scm-api:1.25.5
blueocean-rest:1.25.5
blueocean-rest-impl:1.25.5
blueocean-web:1.25.5
bootstrap5-api:5.1.3-7
bouncycastle-api:2.26
branch-api:2.1046.v0ca_37783ecc5
build-monitor-plugin:1.13+build.202205140447
build-timeout:1.21
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.7.4
cloudbees-bitbucket-branch-source:773.v4b_9b_005b_562b_
cloudbees-disk-usage-simple:0.10
cloudbees-folder:6.729.v2b_9d1a_74d673
code-coverage-api:3.0.4
command-launcher:84.v4a_97f2027398
conditional-buildstep:1.4.2
config-file-provider:3.10.0
copyartifact:1.46.4
credentials:1139.veb_9579fca_33b_
credentials-binding:523.vd859a_4b_122e6
cucumber-reports:5.7.3
dark-theme:185.v276b_5a_8966a_e
dashboard-view:2.432.va_712ce35862d
data-tables-api:1.12.1-2
discord-notifier:206.vee9f4569ee63
display-url-api:2.3.6
docker-commons:1.19
docker-workflow:1.29
dtkit-api:3.0.1
durable-task:496.va67c6f9eefa7
echarts-api:5.3.3-1
email-ext:2.89
embeddable-build-status:237.v37e2c03964c9
extended-read-permission:3.2
external-monitor-job:191.v363d0d1efdf8
favorite:2.4.1
file-operations:1.11
font-awesome-api:6.1.1-1
forensics-api:1.15.1
git:4.11.3
git-client:3.11.0
gitea:1.4.3
github:1.34.4
github-api:1.303-400.v35c2d8258028
github-branch-source:1656.v77eddb_b_e95df
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.30
http_request:1.15
jackson2-api:2.13.3-285.vc03c0256d517
javax-activation-api:1.2.0-3
javax-mail-api:1.6.2-6
jaxb:2.3.6-1
jdk-tool:1.5
jenkins-design-language:1.25.5
jjwt-api:0.11.5-77.v646c772fddb_0
jquery3-api:3.6.0-4
jsch:0.1.55.2
junit:1119.1121.vc43d0fc45561
locale:180.v207501dff9b_a_
lockable-resources:2.15
log-file-filter:76.v43e83b7e1163
mailer:414.vcc4c33714601
matrix-auth:3.1.5
matrix-project:772.v494f19991984
metrics:4.1.6.2
mina-sshd-api-common:2.8.0-30.vf9df64641cb_d
mina-sshd-api-core:2.8.0-30.vf9df64641cb_d
momentjs:1.1.1
mqtt-notification-plugin:1.8
muuri-api:0.9.5-3
nodejs:1.5.1
okhttp-api:4.9.3-105.vb96869f8ac3a
opencover:1.0.3
parameterized-trigger:2.45
pipeline-build-step:2.18
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-groovy-lib:593.va_a_fc25d520e9
pipeline-input-step:449.v77f0e8b_845c4
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2097.v33db_b_de764b_e
pipeline-model-definition:2.2097.v33db_b_de764b_e
pipeline-model-extensions:2.2097.v33db_b_de764b_e
pipeline-rest-api:2.24
pipeline-stage-step:293.v200037eefcd5
pipeline-stage-tags-metadata:2.2097.v33db_b_de764b_e
pipeline-stage-view:2.24
pipeline-utility-steps:2.13.0
plain-credentials:1.8
plugin-util-api:2.17.0
popper2-api:2.11.5-2
prism-api:1.28.0-2
project-stats-plugin:0.4
prometheus:2.0.11
publish-over:0.22
publish-over-ftp:1.17
publish-over-ssh:1.24
pubsub-light:1.16
pull-request-monitoring:1.7.8
resource-disposer:0.19
robot:3.2.0
run-condition:1.5
scm-api:608.vfa_f971c5a_a_e9
script-security:1175.v4b_d517d6db_f0
select2-api:4.0.13-8
seleniumhtmlreport:1.1
sidebar-link:2.2.0
simple-theme-plugin:103.va_161d09c38c7
snakeyaml-api:1.30.2-76.vc104f7ce9870
sonar:2.14
sse-gateway:1.25
ssh-credentials:291.v8211e4f8efb_c
ssh-slaves:1.834.v622da_57f702c
sshd:3.242.va_db_9da_b_26a_c3
strict-crumb-issuer:2.1.0
structs:318.va_f3ccb_729b_71
testng-plugin:555.va0d5f66521e3
theme-manager:1.4
token-macro:293.v283932a_0a_b_49
trilead-api:1.67.vc3938a_35172f
variant:1.4
webhook-step:173.vfa_b_93560b_977
windows-slaves:1.8.1
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1188.v0016b_4f29881
workflow-basic-steps:969.vc4ec3e4854b_f
workflow-cps:2746.v0da_83a_332669
workflow-durable-task-step:1174.v73a_9a_17edce0
workflow-job:1207.ve6191ff089f8
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:625.vd896b_f445a_f8
workflow-support:833.va_1c71061486b_
ws-cleanup:0.42
xunit:3.1.0

### What Operating System are you using (both controller, and any agents involved in the problem)?

Doesn't matter.

### Reproduction steps

1. Publish the report
2. You can find the reports in the traditional view.
3. In Blue

### Expected Results

A summary of the test results appears in the tests tab in BlueOcean's pipeline view.
Together with the prometheus plugin, it should also give metrics there.
Works perfectly fine with robot reports, which appear in this tab.

### Actual Results

Nothing is visible in the tab view — also no metrics in prometheus.

### Anything else?

Nope

**Comment by jonesbusy** [comment]
Plugin is deprecated and user must switch to the coverage plugin that now integrates the OpenCover format
