### ISSUE TITLE
Deprecate plugin

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/opencover-plugin#41]
Hey @jonesbusy,

this plugin depends on the code-coverage-api-plugin plugin, which is deprecated and end of life in favor of https://github.com/jenkinsci/coverage-plugin#jenkins-coverage-plugin.

Would you object to deprecating this plugin, given OpenCover is now included in the standardized coverage plugin?

**Comment by jonesbusy** [comment]
Hi,

Yes it was on my todo list

It wanted to do it in the next few days or some weeks maximum (Perhaps waiting the release of 2.426.3).

Thanks!

**Comment by NotMyFault** [comment]
That's great to hear! If you need help with something, don't hesitate to shoot me a ping or take a look at the [docs](https://www.jenkins.io/doc/developer/plugin-governance/deprecating-or-removing-plugin/).
