### ISSUE TITLE
NullPointerException while publish coverage report (v1.02)

### ISSUE THREAD

**Issue by chehomovns** [jenkinsci/opencover-plugin#6]
After release 1.02 i get NullPointer while try to publish coverage report.  
I run it with command in Jenkins: `publishCoverage adapters: [opencoverAdapter(mergeToOneReport: true, path: 'openCoverCoverage*.xml')], sourceFileResolver: sourceFiles('NEVER_STORE')`  
After tests end i got this: 
![image](https://user-images.githubusercontent.com/48719713/71446014-11df9400-2730-11ea-8ccd-41066028b7c5.png)

**Comment by tempora-mutantur** [comment]
@chehomovns Can you, please, provide your opencover report?

**Comment by chehomovns** [comment]
@tempora-mutantur Sorry there is information i can't share. But i check what generated report is ok with this [tool](https://danielpalme.github.io/ReportGenerator/) and all work well. I can check specific place in this report if u need

**Comment by tempora-mutantur** [comment]
@chehomovns 
Released 1.0.3.
It should be available for download.
Fixed a couple of cases, one of those, very likely, was yours.
Please, try it, and in case it won't help - we'll go through your file and check what is the reason.
Thank you.

**Comment by chehomovns** [comment]
Thank you. Now it's work well.
