### ISSUE TITLE
[Bug] Only one report is discovered

### ISSUE THREAD

**Issue by msallin** [jenkinsci/opencover-plugin#8]
Hi

I do the following call:

`publishCoverage adapters: [opencoverAdapter(mergeToOneReport: true, path: 'tests/**/*opencover*.xml')], sourceFileResolver: sourceFiles('STORE_LAST_BUILD')`

Only one report is discovered. However, there are two. I use other tools with the same path and they discover both correctly. I'm not sure in which repo this issue needs to be reported (see https://github.com/jenkinsci/code-coverage-api-plugin/issues/157).

Thanks for your support.

Marc

**Comment by tempora-mutantur** [comment]
@msallin 
Hi.

Can you, please, give some more details. How do you observe that you have only one reports instead of two.

I made a test and see that there are two reports displayed correctly.

I see, that you're using the `mergeToOneReport` publishing option, this way your reports will get squashed (with no lines overlap merging)[https://github.com/jenkinsci/code-coverage-api-plugin/issues/125]. Maybe that is what you didn't pay attention to?

Thank you.

**Comment by msallin** [comment]
Hi 

Here are the relevant log entires:

[Pipeline] publishCoverage
10:56:23  Publishing Coverage report....
**10:56:23  A total of 1 reports were found**
10:56:23  Source File Navigation is enabled - Current level: STORE_LAST_BUILD
10:56:23  0 source files need to be copied.

My two reports look like this.

10:56:17  +---------+--------+--------+--------+
10:56:17  |         | Line   | Branch | Method |
10:56:17  +---------+--------+--------+--------+
10:56:17  | Total   | 86.05% | 66.97% | 73.2%  |
10:56:17  +---------+--------+--------+--------+
10:56:17  | Average | 60.14% | 54.88% | 48.83% |
10:56:17  +---------+--------+--------+--------+

10:56:22  +---------+--------+--------+--------+
10:56:22  |         | Line   | Branch | Method |
10:56:22  +---------+--------+--------+--------+
10:56:22  | Total   | 48.99% | 48.45% | 33.95% |
10:56:22  +---------+--------+--------+--------+
10:56:22  | Average | 55.44% | 42.97% | 55.32% |
10:56:22  +---------+--------+--------+--------+

Only the second one is found and represented (48.99% line cov). They do overlap. From the other other issue, I don't understand what this means. Can you elaborate?

Btw. I use the cli tool "ReportGenerator" mentioned by you in the other issue, to generate three reports as well (unit tests only, integration tests only, combied). The ReportGenerator is able to detect both files, when using the same path.

**Comment by tempora-mutantur** [comment]
@msallin 

The `A total of 1 reports were found` string is the result of the `mergeToOneReport` option.

> Only the second one is found and represented (48.99% line cov). They do overlap. From the other other issue, I don't understand what this means. Can you elaborate?

This means that plugins based on the code-coverage-api plugin, including opencover, don't merge lines and branches between two reports if they overlap in assemblies/packages/etc.
If you launch `publishCoverage` with the `mergeToOneReport` option it won't be looking through your reports to combine the covered lines/branches. You could have multiple reports, for, let's say, different unit test assemblies that test common assemblies of your code, that you would want to merge to see your overall code coverage, like:

![image](https://user-images.githubusercontent.com/19176095/80398078-c5fc5180-88bf-11ea-8a0f-60b4a8ff9299.png)

Here you see two reports for test assemblies that test the same dll. If you publish them with `mergeToOneReport`,  the result would be 100/138 for lines. 


So, you need to first merge such reports with tools like ReportGenerator into one, which can merge them while looking at exact covered/uncovered lines.

![image](https://user-images.githubusercontent.com/19176095/80399284-a2d2a180-88c1-11ea-9dea-672580a5ecbc.png)

And then publish it using publishCoverage. 

The `mergeToOneReport` option would just combine those results. You may wan't two completely different reports to be represented as one and this can be achieved using it.

**Comment by msallin** [comment]
Thank you! Combining the reports with ReportGenerator and then publish them works.

For the records:

`dotnetToolRun(toolName: 'reportgenerator', parameters: '"-reports:./tests/**/*opencover*.xml" "-targetdir:coveragereport-combined" "-reporttypes:HTMLInline;Cobertura"')
                    archiveArtifacts allowEmptyArchive: false, artifacts: 'coveragereport-combined/*'
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'coveragereport-combined', reportFiles: 'index.htm', reportName: 'Code Coverage Combined', reportTitles: ''])

                    publishCoverage adapters: [istanbulCoberturaAdapter('coveragereport-combined/Cobertura.xml')], calculateDiffForChangeRequests: true, sourceFileResolver: sourceFiles('NEVER_STORE')`

However, ReportGenerator doesn't support to combine two reports into a new OpenCover Report and using istanbulCoberturaAdapter takes more than 2min (~2k LoC). 

Do you plan to implement a functionality like I would have expected from "mergeToOneReport" in your plug-in? At least parsing one report was much faster with this plug-in.
